Repository InditexTech/gh-sherpa, pull requests merged in 2024-01, with the labels that each got.

#49 Remove quotes from `main` branch in sonar execution
  .github/workflows/default-branch-analysis.yml
Labels: kind/internal

#54 Remove license from files and use a folder license approach
  .reuse/dep5
  cmd/create_branch/cmd.go
  cmd/create_pull_request/cmd.go
  cmd/root.go
  internal/branches/branches.go
  internal/branches/branches_test.go
  internal/branches/interactive.go
  internal/config/branches.go
  internal/config/configuration.go
  internal/config/configuration_test.go
  internal/config/github.go
  internal/config/jira.go
  internal/config/parser.go
  internal/config/parser_test.go
  internal/domain/config.go
  internal/domain/issue.go
  internal/domain/issue_tracker.go
  internal/domain/issue_types/issue_type.go
  internal/domain/label.go
  internal/domain/providers.go
  internal/domain/pull_request.go
  internal/domain/repository.go
  internal/gh/cli.go
  internal/gh/cli_test.go
  internal/git/git.go
  internal/git/git_test.go
  internal/interactive/interactive.go
  internal/issue_trackers/github/github.go
  internal/issue_trackers/github/github_test.go
  internal/issue_trackers/issue_trackers.go
  internal/issue_trackers/jira/jira.go
  internal/issue_trackers/jira/jira_test.go
  internal/logging/colors.go
  internal/logging/logging.go
  internal/mocks/domain/mock_BranchProvider.go
  internal/mocks/domain/mock_ConfigProvider.go
  internal/mocks/domain/mock_GhCli.go
  internal/mocks/domain/mock_GitProvider.go
  internal/mocks/domain/mock_IssueTracker.go
  internal/mocks/domain/mock_IssueTrackerProvider.go
  internal/mocks/domain/mock_PullRequestProvider.go
  internal/mocks/domain/mock_RepositoryProvider.go
  internal/mocks/domain/mock_UserInteractionProvider.go
  internal/mocks/utils.go
  internal/use_cases/create_branch.go
  internal/use_cases/create_branch_test.go
  internal/use_cases/create_pull_request.go
  internal/use_cases/create_pull_request_test.go
  main.go
  pkg/metadata/metadata.go
  pkg/validator/custom.go
  pkg/validator/custom_test.go
  pkg/validator/error_messages.go
  pkg/validator/validator.go
Labels: kind/internal

#57 Add CLA signature requirement to contribute in CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: kind/documentation

#51 Add GitHub issue type label to the generated pull request
  internal/branches/interactive.go
  internal/domain/issue_tracker.go
  internal/domain/providers.go
  internal/gh/cli.go
  internal/gh/cli_test.go
  internal/git/git.go
  internal/issue_trackers/github/github.go
  internal/issue_trackers/github/github_test.go
  internal/issue_trackers/issue_trackers.go
  internal/issue_trackers/jira/jira.go
  internal/issue_trackers/jira/jira_test.go
  internal/mocks/domain/mock_IssueTracker.go
  internal/mocks/domain/mock_PullRequestProvider.go
  internal/use_cases/create_branch_test.go
  internal/use_cases/create_pull_request.go
  internal/use_cases/create_pull_request_test.go
Labels: kind/feature

#59 Prepare 1.1.0 release
  CHANGELOG.md
  version
Labels: release

#61 Disable cgo when cross building distributables
  dist.sh
Labels: kind/internal

#64 Add `SECURITY.md` file
  README.md
  SECURITY.md
  repolinter.json
Labels: kind/documentation
