Repository InditexTech/gh-sherpa, pull requests merged in 2024-05, with the labels that each got.

#79 Warns about duplicated branches but that's not the case
  internal/use_cases/create_pull_request.go
Labels: kind/bug

#82 Add REUSE Compliance workflow
  .github/workflows/PR-verify.yml
  .github/workflows/sonar-branch-analysis.yml
Labels: kind/feature

#81 Prevent pushing local branch if remote branch already exists with the same name
  .github/workflows/PR-verify.yml
  .github/workflows/release.yml
  .github/workflows/sonar-branch-analysis.yml
  internal/use_cases/create_pull_request.go
  internal/use_cases/create_pull_request_test.go
  sonar-project.properties
Labels: kind/bug

#86 Use fakes instead of mocks for use case tests
  internal/domain/providers.go
  internal/fakes/domain/fake_branch_provider.go
  internal/fakes/domain/fake_gh_cli.go
  internal/fakes/domain/fake_git_provider.go
  internal/fakes/domain/fake_issue_tracker.go
  internal/fakes/domain/fake_issue_tracker_provider.go
  internal/fakes/domain/fake_pull_request_provider.go
  internal/fakes/domain/fake_repository_provider.go
  internal/fakes/domain/fake_user_interaction_provider.go
  internal/interactive/interactive.go
  internal/use_cases/create_branch_test.go
  internal/use_cases/create_pull_request_test.go
  sonar-project.properties
Labels: kind/refactoring

#90 Refactor domain issue and avoid injection
  internal/branches/branches.go
  internal/branches/branches_test.go
  internal/branches/interactive.go
  internal/domain/issue.go
  internal/domain/issue_tracker.go
  internal/domain/providers.go
  internal/fakes/domain/fake_branch_provider.go
  internal/fakes/domain/fake_issue.go
  internal/fakes/domain/fake_issue_tracker.go
  internal/fakes/domain/fake_issue_tracker_provider.go
  internal/issue_trackers/github/github.go
  internal/issue_trackers/github/github_test.go
  internal/issue_trackers/github/issue.go
  internal/issue_trackers/issue_trackers.go
  internal/issue_trackers/jira/client.go
  internal/issue_trackers/jira/issue.go
  internal/issue_trackers/jira/jira.go
  internal/issue_trackers/jira/jira_test.go
  internal/mocks/domain/mock_BranchProvider.go
  internal/mocks/domain/mock_Issue.go
  internal/mocks/domain/mock_IssueTrackerProvider.go
  internal/mocks/domain/mock_PullRequestProvider.go
  internal/use_cases/create_branch.go
  internal/use_cases/create_branch_test.go
  internal/use_cases/create_pull_request.go
  internal/use_cases/create_pull_request_test.go
Labels: kind/refactoring
